version: 0.0  # CodeDeploy 버전
os: linux
files:
  - source: webgoat-2023.9-SNAPSHOT.jar  # buildspec.yml에서 생성된 아티팩트 경로에 맞춰 수정
    destination: /home/ec2-user/build/  # 파일을 복사할 대상 경로
    overwrite: yes

permissions:  # 파일 권한 설정
  - object: /home/ec2-user/build/webgoat-2023.9-SNAPSHOT.jar  # 복사된 파일에 대한 권한 설정
    owner: ec2-user
    group: ec2-user
    mode: 755
    
hooks:
  AfterInstall:  # 배포를 완료한 후 실행되는 스크립트
    - location: start.sh
      timeout: 60
      runas: ec2-user
