version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17  
  pre_build:
    commands:
      - echo Nothing to do in the pre_build phase...

  build:
    commands:
      - echo Building started on 'date'...
      - pwd && ls && whoami
      - ./mvnw clean install -D skipTests

      # OWASP ZAP 다운로드 및 압축 해제
      - sudo wget https://github.com/zaproxy/zaproxy/releases/download/v2.15.0/ZAP_2.15.0_Linux.tar.gz
      - sudo tar -xvf ZAP_2.15.0_Linux.tar.gz
      - cd ZAP_2.15.0

      # ZAP를 명령줄에서 직접 실행하여 대상 웹사이트(WebGoat)에 대해 빠른 스캔 수행 및 리포트 저장
      - sudo ./zap.sh -cmd -quickurl http://BlueGreen-jw-87223296.ap-northeast-2.elb.amazonaws.com/WebGoat -quickprogress -quickout ../zap_report.html

      # 리포트 파일이 생성되었는지 확인
      - ls -l ../zap_report.html


  post_build:
    commands:
      - echo Build completed on `date`
      # ZAP 인증서를 덤프하여 파일로 생성 (HTTPS 테스트 필요시)
      - sudo ./zap.sh -cmd -certfulldump zap.crt

      # 인증서를 OpenSSL 인증서 디렉터리에 복사
      - sudo cp zap.crt /usr/local/share/ca-certificates/
      - sudo update-ca-certificates

      # 리포트 파일 내용 확인
      - cat ../zap_report.html

artifacts:
  files:
    - target/webgoat-2023.9-SNAPSHOT.jar
    - appspec.yml
    - start.sh
    - zap_report.html
