version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17
    commands:
      - echo Installing CycloneDX CLI...
      - npm install -g @cyclonedx/bom  # CycloneDX Generator 설치

  pre_build:
    commands:
      - echo Nothing to do in the pre_build phase...
      

  build:
    commands:
      - echo Building started on 'date'...
      - pwd && ls && whoami
      - ./mvnw clean install -D skipTests


  post_build:
    commands:
      - echo Build completed on `date`
      - echo Generating SBOM with CycloneDX...
      - cyclonedx-bom -o sbom.xml  # SBOM 파일 생성

artifacts:
  files:
    - target/webgoat-2023.9-SNAPSHOT.jar
    - sbom.xml
    - appspec.yml
    - start.sh
