version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17  
  pre_build:
    commands:
      - echo Nothing to do in the pre_build phase...

  build:
    commands:
      - echo Building started on 'date'...
      - pwd && ls && whoami
      - ./mvnw clean install -D skipTests  

  post_build:
    commands:
      - echo Build completed on `date`

artifacts:
  files:
    - target/webgoat-2023.9-SNAPSHOT.jar
    - appspec.yml
    - start.sh
